### ISSUE TITLE
Error message UI issues in the Options Page. 

### ISSUE THREAD

**Issue by tihcar18** [tilakcherukuri/pega-dx-dev-tools#64]
The error message is not coming as red or highlighted and is immediately disappearing on clicking + symbol when the constellation url is not configured.
![image](https://user-images.githubusercontent.com/10088075/198184018-205f27b3-bba8-46ad-aa04-290a9ad4a5f3.png)

**Comment by Kalyan-Gutala** [comment]
Addressed and Resolved
