### ISSUE TITLE
Insights tab is showing the Optional Network calls 

### ISSUE THREAD

**Issue by kadiyamshivaji** [tilakcherukuri/pega-dx-dev-tools#71]
Insights tab is showing the Optional Network calls  
Note: In API traffic optional network calls are filtered.

**Comment by TusharPega** [comment]
![network](https://user-images.githubusercontent.com/115024801/198189038-b0cebb25-c727-4532-bdea-64d979a4d14a.png)
![Insight](https://user-images.githubusercontent.com/115024801/198189040-0f08ceaa-0064-4836-8e15-ae775b38f5cc.png)

**Comment by kadiyamshivaji** [comment]
Fixed
